name: CI/CD for Node.js with Docker

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker using official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Build Docker image
        run: |
          docker build -t mayank0809/flipkart-image:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "mayank0809" --password-stdin
          docker push mayank0809/flipkart-image:latest

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 mayank0809/flipkart-image:latest
